from __future__ import annotations

from pathlib import Path


def write_fake_docker_runtime(path: Path) -> None:
    path.write_text(
        "\n".join(
            [
                "#!/usr/bin/env python3",
                "import json, os, sys, time",
                "args = sys.argv[1:]",
                "image_digest = os.environ.get('FAKE_DOCKER_IMAGE_DIGEST', 'sha256:image')",
                "container_id = os.environ.get('FAKE_DOCKER_CONTAINER_ID', 'container-123')",
                "container_name = os.environ.get('FAKE_DOCKER_CONTAINER_NAME', 'vela-qwen')",
                "log = os.environ.get('FAKE_DOCKER_COMMAND_LOG')",
                "state_file = os.environ.get('FAKE_DOCKER_STATE_FILE')",
                "def write_state(value):",
                "    if state_file:",
                "        with open(state_file, 'w', encoding='utf-8') as file:",
                "            file.write(value)",
                "def read_state():",
                "    if not state_file:",
                "        return ''",
                "    try:",
                "        with open(state_file, 'r', encoding='utf-8') as file:",
                "            return file.read().strip()",
                "    except FileNotFoundError:",
                "        return ''",
                "if log:",
                "    with open(log, 'a', encoding='utf-8') as file:",
                "        file.write(' '.join(args) + '\\n')",
                "if args[:2] == ['image', 'inspect']:",
                "    if os.environ.get('FAKE_DOCKER_IMAGE_MISSING') == '1':",
                "        print('Error: No such image: ' + args[-1], file=sys.stderr)",
                "        raise SystemExit(1)",
                "    payload = [{",
                "        'Id': image_digest,",
                "        'RepoDigests': ['vllm/vllm-openai@' + image_digest],",
                "    }]",
                "    print(json.dumps(payload))",
                "    raise SystemExit(0)",
                "if args[:1] == ['pull']:",
                "    if os.environ.get('FAKE_DOCKER_PULL_FAIL') == '1':",
                "        print('pull failed for ' + args[-1], file=sys.stderr)",
                "        raise SystemExit(1)",
                "    print('Pulling from library/' + args[-1], flush=True)",
                "    print('Downloading [====>      ]  2.5GB/10GB', flush=True)",
                "    raw_sleep = os.environ.get('FAKE_DOCKER_PULL_SLEEP_SECONDS', '0') or '0'",
                "    pull_sleep = float(raw_sleep)",
                "    if pull_sleep:",
                "        time.sleep(pull_sleep)",
                "    print('Status: Downloaded newer image for ' + args[-1], flush=True)",
                "    raise SystemExit(0)",
                "if args[:2] == ['run', '-d']:",
                "    write_state('running')",
                "    print(container_id)",
                "    raise SystemExit(0)",
                "if args[:1] == ['ps']:",
                "    print(os.environ.get('FAKE_DOCKER_PS', ''))",
                "    raise SystemExit(0)",
                "if args[:2] == ['logs', '-f']:",
                "    print('INFO Uvicorn running on http://0.0.0.0:8000', flush=True)",
                "    raise SystemExit(0)",
                "if args[:1] == ['wait']:",
                "    wait_seconds = float(os.environ.get('FAKE_DOCKER_WAIT_SECONDS', '0') or '0')",
                "    deadline = time.time() + wait_seconds",
                "    while wait_seconds and read_state() not in {'stopped', 'killed'}:",
                "        if time.time() >= deadline:",
                "            break",
                "        time.sleep(0.05)",
                "    print('0')",
                "    raise SystemExit(0)",
                "if args[:1] == ['inspect']:",
                "    state = read_state()",
                "    if not state:",
                "        state = os.environ.get('FAKE_DOCKER_CONTAINER_STATE', 'running')",
                "    running = state == 'running'",
                "    payload = [{",
                "        'Id': container_id,",
                "        'Name': '/' + container_name,",
                "        'Image': image_digest,",
                "        'Config': {'Image': 'vllm/vllm-openai@' + image_digest},",
                "        'RepoDigests': ['vllm/vllm-openai@' + image_digest],",
                "        'State': {'Running': running},",
                "    }]",
                "    print(json.dumps(payload))",
                "    raise SystemExit(0)",
                "if args[:1] == ['stop']:",
                "    write_state('stopped')",
                "    raise SystemExit(0)",
                "if args[:1] == ['kill']:",
                "    write_state('killed')",
                "    raise SystemExit(0)",
                "if args[:1] == ['rm']:",
                "    raise SystemExit(0)",
                "raise SystemExit(f'unexpected docker args: {args}')",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    path.chmod(0o755)
