from __future__ import annotations

from pathlib import Path


def write_fake_ssh_runtime(path: Path) -> None:
    path.write_text(
        "\n".join(
            [
                "#!/usr/bin/env python3",
                "import json, os, sys",
                "",
                "args = sys.argv[1:]",
                "",
                "def getenv(name, default=''):",
                "    return os.environ.get(name, default)",
                "",
                "def truthy(name, default='0'):",
                "    return getenv(name, default).lower() in {'1', 'true', 'yes', 'on'}",
                "",
                "def split_remote(argv):",
                "    value_options = {'-B', '-b', '-c', '-E', '-e', '-i', '-J', '-m', '-o', '-p'}",
                "    index = 0",
                "    while index < len(argv):",
                "        item = argv[index]",
                "        if item == '--':",
                "            index += 1",
                "            break",
                "        if not item.startswith('-'):",
                "            return item, ' '.join(argv[index + 1:])",
                "        if item in value_options and index + 1 < len(argv):",
                "            index += 2",
                "            continue",
                "        index += 1",
                "    if index < len(argv):",
                "        return argv[index], ' '.join(argv[index + 1:])",
                "    return '', ''",
                "",
                "host, remote_command = split_remote(args)",
                "log_path = getenv('FAKE_SSH_COMMAND_LOG')",
                "if log_path:",
                "    with open(log_path, 'a', encoding='utf-8') as file:",
                "        file.write(json.dumps({",
                "            'args': args,",
                "            'host': host,",
                "            'remote_command': remote_command,",
                "        }, sort_keys=True) + '\\n')",
                "",
                "if getenv('FAKE_SSH_EXIT_CODE'):",
                "    stderr = getenv('FAKE_SSH_STDERR')",
                "    if stderr:",
                "        print(stderr, file=sys.stderr)",
                "    raise SystemExit(int(getenv('FAKE_SSH_EXIT_CODE')))",
                "",
                "if truthy('FAKE_SSH_UNREACHABLE'):",
                "    print(",
                "        getenv('FAKE_SSH_UNREACHABLE_STDERR', 'Permission denied (publickey).'),",
                "        file=sys.stderr,",
                "    )",
                "    raise SystemExit(255)",
                "",
                "vela_present = truthy('FAKE_SSH_VELA_PRESENT', '1')",
                (
                    "vela_path = getenv('FAKE_SSH_VELA_PATH', "
                    "'/home/bgconley/.local/share/vela/venv/bin/vela')"
                ),
                "vela_version = getenv('FAKE_SSH_VELA_VERSION', '1.0.0')",
                "",
                "def command_not_found(command='vela'):",
                "    print(f'sh: 1: {command}: not found', file=sys.stderr)",
                "    raise SystemExit(127)",
                "",
                "def print_host_report():",
                "    payload = getenv('FAKE_SSH_HOST_REPORT_JSON')",
                "    if payload:",
                "        print(payload)",
                "        return",
                "    print(json.dumps({",
                "        'hostname': getenv('FAKE_SSH_HOSTNAME', 'fake-remote'),",
                "        'platform': getenv('FAKE_SSH_PLATFORM', 'Linux'),",
                "        'python': getenv('FAKE_SSH_PYTHON', '/usr/bin/python3'),",
                "        'uv_available': truthy('FAKE_SSH_UV_AVAILABLE'),",
                "        'cuda': getenv('FAKE_SSH_CUDA', '13.0'),",
                "        'driver': getenv('FAKE_SSH_DRIVER', '590.48.01'),",
                "        'gpu': getenv('FAKE_SSH_GPU', 'NVIDIA RTX PRO 6000 Blackwell'),",
                "    }, sort_keys=True))",
                "",
                "def run_install():",
                "    if truthy('FAKE_SSH_INSTALL_SUCCESS', '1'):",
                "        print(getenv('FAKE_SSH_INSTALL_STDOUT', f'installed {vela_path}'))",
                "        return",
                "    print(getenv('FAKE_SSH_INSTALL_STDERR', 'install failed'), file=sys.stderr)",
                "    raise SystemExit(int(getenv('FAKE_SSH_INSTALL_EXIT_CODE', '1')))",
                "",
                "def run_agent():",
                "    if not vela_present:",
                "        command_not_found('vela')",
                "    for line in sys.stdin:",
                "        if not line.strip():",
                "            continue",
                "        frame = json.loads(line)",
                "        request_id = str(frame.get('id', ''))",
                "        method = frame.get('method')",
                "        params = frame.get('params') or {}",
                "        if method == 'handshake':",
                "            result = {",
                "                'target': getenv('FAKE_SSH_TARGET', 'blackbird'),",
                "                'agent_version': vela_version,",
                "                'protocol_version': params.get('protocol_version'),",
                "                'host_info': {",
                "                    'hostname': getenv('FAKE_SSH_HOSTNAME', 'fake-remote'),",
                "                    'platform': getenv('FAKE_SSH_PLATFORM', 'Linux'),",
                "                },",
                "            }",
                "            print(json.dumps({'id': request_id, 'result': result}), flush=True)",
                "            continue",
                "        if method == 'ping':",
                (
                    "            print(json.dumps({'id': request_id, "
                    "'result': {'ok': True}}), flush=True)"
                ),
                "            continue",
                "        print(json.dumps({",
                "            'id': request_id,",
                "            'error': {",
                "                'code': -32601,",
                "                'message': f'unknown fake ssh method: {method}',",
                "            },",
                "        }), flush=True)",
                "",
                "if 'agent connect' in remote_command:",
                "    run_agent()",
                "    raise SystemExit(0)",
                "",
                "if 'command -v vela' in remote_command:",
                "    if vela_present:",
                "        print(vela_path)",
                "        raise SystemExit(0)",
                "    raise SystemExit(1)",
                "",
                "version_probe = '--version' in remote_command and (",
                "    'vela' in remote_command or 'python3 -m vela' in remote_command",
                ")",
                "if version_probe:",
                "    if vela_present or 'python3 -m vela' in remote_command:",
                "        print(vela_version)",
                "        raise SystemExit(0)",
                "    command_not_found('vela')",
                "",
                "if 'pip install' in remote_command or 'python3 -m venv' in remote_command:",
                "    run_install()",
                "    raise SystemExit(0)",
                "",
                "if 'host_report' in remote_command or 'doctor' in remote_command:",
                "    print_host_report()",
                "    raise SystemExit(0)",
                "",
                "print(getenv('FAKE_SSH_DEFAULT_STDOUT', ''))",
                "raise SystemExit(int(getenv('FAKE_SSH_DEFAULT_EXIT_CODE', '0')))",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    path.chmod(0o755)
