from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from pydantic import ValidationError

from vela.config.loader import load_registry
from vela.config.schema import (
    Exposure,
    ModelConfig,
    RuntimeKind,
    default_run_artifacts_dir,
    model_basename,
)
from vela.engine.command_builder import build_command
from vela.engine.profile import VllmProfileError, select_profile_for_config

DEFAULT_PORT_RANGE = (18000, 18999)


@dataclass(frozen=True)
class ComposeResult:
    config: ModelConfig
    warnings: list[str] = field(default_factory=list)
    derived: list[dict[str, str]] = field(default_factory=list)


PRESETS: tuple[dict[str, Any], ...] = (
    {
        "name": "balanced",
        "description": "Default safe starting point for general serving.",
        "engine": {"gpu_memory_utilization": 0.9, "dtype": "auto"},
        "extra_args": ["--enable-prefix-caching"],
        "applies_to": ["all"],
    },
    {
        "name": "throughput",
        "description": "Favor higher batch volume when memory headroom exists.",
        "engine": {"gpu_memory_utilization": 0.92, "dtype": "auto", "max_num_seqs": 32},
        "extra_args": ["--enable-prefix-caching"],
        "applies_to": ["all"],
    },
    {
        "name": "long-context",
        "description": "Reserve memory for longer prompts and conservative concurrency.",
        "engine": {"gpu_memory_utilization": 0.9, "dtype": "auto", "max_num_seqs": 4},
        "extra_args": ["--enable-prefix-caching"],
        "applies_to": ["all"],
    },
    {
        "name": "low-memory",
        "description": "Conservative memory profile for tight cards or experiments.",
        "engine": {"gpu_memory_utilization": 0.85, "dtype": "auto", "max_num_seqs": 2},
        "extra_args": ["--enable-prefix-caching"],
        "applies_to": ["all"],
    },
    {
        "name": "qwen3-text",
        "description": "Qwen3 text serving with reasoning/tool parsers enabled.",
        "engine": {"gpu_memory_utilization": 0.9, "dtype": "auto"},
        "extra_args": [
            "--enable-prefix-caching",
            "--language-model-only",
            "--reasoning-parser",
            "qwen3",
            "--tool-call-parser",
            "qwen3_coder",
        ],
        "applies_to": ["qwen", "qwen3"],
    },
)


def list_presets() -> list[dict[str, Any]]:
    return [
        {
            "name": str(preset["name"]),
            "description": str(preset["description"]),
            "engine": dict(preset.get("engine") or {}),
            "extra_args": list(preset.get("extra_args") or []),
            "applies_to": list(preset.get("applies_to") or []),
        }
        for preset in PRESETS
    ]


def compose_config(spec: dict[str, Any], *, configs_dir: str | Path | None = None) -> ComposeResult:
    model = _required_str(spec, "model")
    name = _deployment_name(spec.get("name"), model)
    target = _optional_str(spec.get("target"))
    runtime = _runtime_kind(spec.get("runtime"))
    overrides = _mapping(spec.get("overrides"), field_name="overrides")
    preset_name = _optional_str(spec.get("preset")) or "balanced"
    preset = _preset_by_name(preset_name)
    port = allocate_port(
        preferred=_preferred_port(overrides),
        configs_dir=configs_dir,
    )["port"]

    payload: dict[str, Any] = {
        "name": name,
        "target": target,
        "model": model,
        "served_model_name": model_basename(model),
        "description": f"Generated by Vela deployment composer using preset {preset_name}.",
        "command": _runtime_command(runtime, spec, name),
        "engine": dict(preset.get("engine") or {}),
        "server": {
            "host": "127.0.0.1",
            "port": port,
            "exposure": Exposure.LOCAL.value,
        },
        "extra_args": list(preset.get("extra_args") or []),
        "launch": {"runs_dir": str(default_run_artifacts_dir() / name)},
    }
    if target is None:
        payload.pop("target")

    _merge_overrides(payload, overrides)
    _merge_extra_args(payload, overrides)
    cfg = ModelConfig.model_validate(payload)
    return ComposeResult(
        config=cfg,
        warnings=[],
        derived=[
            {
                "field": "served_model_name",
                "value": cfg.served_model_name or "",
                "source": "model_basename",
            },
            {"field": "server.port", "value": str(cfg.server.port), "source": "allocate_port"},
            {"field": "launch.runs_dir", "value": str(cfg.launch.runs_dir), "source": "runs_root"},
            *_docker_derived(cfg),
        ],
    )


def allocate_port(
    *,
    preferred: int | None = None,
    configs_dir: str | Path | None = None,
    port_range: tuple[int, int] = DEFAULT_PORT_RANGE,
) -> dict[str, Any]:
    used = _configured_ports(configs_dir)
    start, end = port_range
    scanned = {"configured_ports": sorted(used), "range": [start, end]}
    if preferred is not None and preferred not in used:
        return {"port": preferred, "scanned": scanned, "warnings": []}
    for port in range(start, end + 1):
        if port not in used:
            warnings = ["port-reassigned"] if preferred is not None else []
            return {"port": port, "scanned": scanned, "warnings": warnings}
    raise ValueError(f"no free port in range {start}-{end}")


def suggest_deployment_defaults(
    params: dict[str, Any], *, configs_dir: str | Path | None = None
) -> dict[str, Any]:
    model = _required_str(params, "model")
    name = _deployment_name(params.get("name"), model)
    runtime = _runtime_kind(params.get("runtime"))
    allocation = allocate_port(
        preferred=_optional_int(params.get("preferred_port")),
        configs_dir=configs_dir,
    )
    payload = {
        "served_model_name": model_basename(model),
        "port": allocation["port"],
        "runs_dir": str(default_run_artifacts_dir() / name),
        "exposure": Exposure.LOCAL.value,
        "engine_suggestions": {},
        "sources": ["model_basename", "configured_ports", "defaults"],
    }
    if runtime is RuntimeKind.DOCKER:
        payload["container_name"] = f"vela-{name}"
    return payload


def validate_config_payload(payload: dict[str, Any]) -> dict[str, Any]:
    errors: list[dict[str, str]] = []
    warnings: list[str] = []
    try:
        cfg = ModelConfig.model_validate(payload)
    except ValidationError as exc:
        return {
            "ok": False,
            "errors": [
                {"field": ".".join(str(part) for part in error["loc"]), "message": error["msg"]}
                for error in exc.errors()
            ],
            "warnings": [],
        }
    except Exception as exc:
        return {"ok": False, "errors": [{"field": "config", "message": str(exc)}], "warnings": []}
    warnings.extend(_lint_config(cfg))
    try:
        result = build_command(cfg, select_profile_for_config(cfg))
    except VllmProfileError as exc:
        errors.append({"field": "vllm", "message": str(exc)})
    else:
        warnings.extend(result.warnings)
    return {"ok": not errors, "errors": errors, "warnings": warnings}


def _runtime_command(runtime: RuntimeKind, spec: dict[str, Any], name: str) -> dict[str, Any]:
    runtime_payload = spec.get("runtime")
    if runtime is RuntimeKind.PROCESS:
        if isinstance(runtime_payload, dict) and runtime_payload.get("kind") == "executable":
            executable = _required_str(runtime_payload, "executable")
            return {"runtime": "process", "executable": executable}
        build_ref = spec.get("build") or (
            runtime_payload.get("build") if isinstance(runtime_payload, dict) else None
        )
        if build_ref:
            return {"runtime": "process", "build": str(build_ref)}
        return {"runtime": "process"}
    image = _docker_image(spec)
    return {
        "runtime": "docker",
        "docker": {
            "image": image,
            "container_name": f"vela-{name}",
        },
    }


def _merge_overrides(payload: dict[str, Any], overrides: dict[str, Any]) -> None:
    for section in ("engine", "server", "launch", "env"):
        section_overrides = overrides.get(section)
        if section_overrides is None:
            continue
        if not isinstance(section_overrides, dict):
            raise ValueError(f"overrides.{section} must be a mapping")
        current = dict(payload.get(section) or {})
        current.update(section_overrides)
        payload[section] = current


def _merge_extra_args(payload: dict[str, Any], overrides: dict[str, Any]) -> None:
    if "extra_args" not in overrides:
        return
    extra_args = overrides["extra_args"]
    if not isinstance(extra_args, list) or not all(isinstance(item, str) for item in extra_args):
        raise ValueError("overrides.extra_args must be a list of strings")
    payload["extra_args"] = [*list(payload.get("extra_args") or []), *extra_args]


def _docker_derived(cfg: ModelConfig) -> list[dict[str, str]]:
    if cfg.command.runtime is not RuntimeKind.DOCKER or cfg.command.docker is None:
        return []
    return [
        {
            "field": "command.docker.container_name",
            "value": cfg.command.docker.container_name or "",
            "source": "deployment_name",
        }
    ]


def _configured_ports(configs_dir: str | Path | None) -> set[int]:
    registry = load_registry(configs_dir)
    return {item.config.server.port for item in registry.valid}


def _preset_by_name(name: str) -> dict[str, Any]:
    for preset in PRESETS:
        if preset["name"] == name:
            return preset
    raise ValueError(f"unknown deployment preset: {name}")


def _runtime_kind(value: object) -> RuntimeKind:
    if isinstance(value, dict):
        kind = value.get("kind", "process")
    elif value is None:
        kind = "process"
    else:
        kind = value
    if kind in {"build", "create_build", "adopt", "executable"}:
        return RuntimeKind.PROCESS
    return RuntimeKind(str(kind))


def _docker_image(spec: dict[str, Any]) -> str:
    runtime = spec.get("runtime")
    if isinstance(runtime, dict):
        image = runtime.get("image")
        if image:
            return str(image)
    image = spec.get("image")
    if image:
        return str(image)
    raise ValueError("docker runtime requires image")


def _preferred_port(overrides: dict[str, Any]) -> int | None:
    server = overrides.get("server")
    if isinstance(server, dict):
        return _optional_int(server.get("port"))
    return None


def _required_str(mapping: dict[str, Any], key: str) -> str:
    value = mapping.get(key)
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{key} is required")
    return value.strip()


def _optional_str(value: object) -> str | None:
    if isinstance(value, str) and value.strip():
        return value.strip()
    return None


def _optional_int(value: object) -> int | None:
    if value is None:
        return None
    try:
        return int(value)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"expected integer value: {value!r}") from exc


def _mapping(value: object, *, field_name: str) -> dict[str, Any]:
    if value is None:
        return {}
    if not isinstance(value, dict):
        raise ValueError(f"{field_name} must be a mapping")
    return dict(value)


def _deployment_name(value: object, model: str) -> str:
    explicit = _optional_str(value)
    if explicit:
        return _slug(explicit)
    return _slug(model_basename(model))


def _slug(value: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9_.-]+", "-", value.strip()).strip("-").lower()
    return slug or "deployment"


def _lint_config(cfg: ModelConfig) -> list[str]:
    warnings: list[str] = []
    if cfg.model.startswith(("/", "~")):
        warnings.append("model uses a host-local absolute path; prefer model_ref for portability")
    if cfg.command.executable and cfg.command.executable.startswith(("/", "~")):
        warnings.append("command.executable is host-local; prefer command.build or docker image")
    if cfg.command.cwd and str(cfg.command.cwd).startswith(("/", "~")):
        warnings.append("command.cwd is host-local; verify it exists on the target")
    return warnings
